### ISSUE TITLE
adding/removing sensors causes the site details page to fail

### ISSUE THREAD

**Issue by andyczerwonka** [andyczerwonka/tyrion#112]
All readings for a specific site must be **consistent with the number of configured sensors**.

@mbrigdan logged this issue a while back. For the Oil Show milestone, we will work around it by not changing sensors once they're configured. 

```
play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: transpose requires all collections have the same size]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.8.jar:2.3.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: java.lang.IllegalArgumentException: transpose requires all collections have the same size
	at scala.collection.generic.GenericTraversableTemplate$class.fail$1(GenericTraversableTemplate.scala:213) ~[scala-library-2.11.6.jar:na]
	at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:220) ~[scala-library-2.11.6.jar:na]
	at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:219) ~[scala-library-2.11.6.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
	at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1.apply(GenericTraversableTemplate.scala:219) ~[scala-library-2.11.6.jar:na]
```

**Comment by andyczerwonka** [comment]
The `transpose` function is the culprit here.
https://github.com/andyczerwonka/tyrion/blob/master/app/models/SiteInfo.scala#L28

**Comment by andyczerwonka** [comment]
Fixed.
