### ISSUE TITLE
handle changes in site sensors

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#83]
Site appears red on the dashboard, and trying to see the summary of the site shows the basic menus (system admin, link to main page) but nothing else.

Console displays error:
```
[error] application - 

! @6lm9gpg6i - Internal server error, for (GET) [/api/summary/sites/552050b05218fdda72317ea6] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: transpose requires all collections have the same size]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.lang.IllegalArgumentException: transpose requires all collections have the same size
        at scala.collection.generic.GenericTraversableTemplate$class.fail$1(GenericTraversableTemplate.scala:213) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1.apply(GenericTraversableTemplate.scala:225) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1.apply(GenericTraversableTemplate.scala:217) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.immutable.Stream.foreach(Stream.scala:594) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.generic.GenericTraversableTemplate$class.transpose(GenericTraversableTemplate.scala:217) ~[org.scala-lang.scala-library-2.11.6.jar:na]
```
Let me know if you need any other files to help debug

**Comment by andyczerwonka** [comment]
@mbrigdan is that the entire stack trace?

**Comment by andyczerwonka** [comment]
@mbrigdan can you send me the result of the following query:

```
db.readings.find({ siteId: ObjectId("552050b05218fdda72317ea6") })
```

**Comment by andyczerwonka** [comment]
Ok, I think I found it. https://github.com/andyczerwonka/tyrion/blob/master/app/models/SiteInfo.scala#L14

The code assumes, incorrectly, that all reading arrays for the same site will be the same size, i.e. the number of sensors will never change. Can you confirm that that your data set has inconsistent set of reading values?

**Comment by mbrigdan** [comment]
@andyczerwonka I don't think I ever intentionally changed the numbers of sensors for the site, but its possible my client screwed up and sent something strange, but I think your site shouldn't have accepted the reading in that case. Here's the result of the query

https://gist.github.com/mbrigdan/7804c09d6e8c6c36ec93

**Comment by andyczerwonka** [comment]
@mbrigdan The query shows what I suspected, a few records that show `[]`. I think it's a valid case for sensors to appear and disappear at points in time. It's going to be tricky and the positional structure may not suffice. While the fix for your issue is somewhat trivial, I think it uncovers a protocol issue that I think needs more analysis.

**Comment by mbrigdan** [comment]
@andyczerwonka That makes sense. Besides dealing with a changing number of sensors, I wonder how those empty records got there in the first place.  When I was first setting it up, the website threw an exception if the submitted reading had the wrong number of sensors or was formatted wrong, and didn't log any data, so I don't know what would have created those empty readings.

**Comment by andyczerwonka** [comment]
Hmmm... not sure. I could be either a bug in the server side or the client side.

**Comment by andyczerwonka** [comment]
I've renamed this to change the internal data structures to better handle changes in sensor configuration.
