### ISSUE TITLE
Unresolved dependency in latest build

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#93]
Trying to use commit 5432ea78105a0ab504e76fdda6504c56bcdeeb00, attempting to start the application results in
```
[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7 ...
[warn]  module not found: org.scalaz.stream#scalaz-stream_2.11;0.7
[warn] ==== local: tried
[warn]   /home/hydra/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/home/hydra/tyrion/activator-1.2.10-minimal/repository/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[info] Resolving com.typesafe.trace#trace-sigar-libs;0.1.6 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.scalaz.stream:scalaz-stream_2.11:0.7
[warn]            +- org.specs2:specs2-common_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3
[warn]            +- org.specs2:specs2-matcher_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3
[warn]            +- org.specs2:specs2-core_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn]            +- org.specs2:specs2-analysis_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn]            +- org.specs2:specs2-matcher-extra_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn]            +- tyrion:tyrion_2.11:2014.1-DEV
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7: not found

Cannot start with errors.
```

Based on some googling, I added the line
```
//scalaz repo
resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"
```
to projects/plugins.sbt , but that didn't help.

**Comment by andyczerwonka** [comment]
@mbrigdan No, don't make any changes. If you made this change locally, do a git reset to clean out your change. When you see unresolved deeps, it just means that I updates libraries. Run 'activator update' and that will pull in the new deps. You can just run that every time you pull new changes.

**Comment by mbrigdan** [comment]
@andyczerwonka Trying to update fails the same way
```
./activator-1.2.10-minimal/activator update
[info] Loading project definition from /home/hydra/tyrion/project
[info] Set current project to tyrion (in build file:/home/hydra/tyrion/)
[info] Updating {file:/home/hydra/tyrion/}tyrion...
[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7 ...
[warn] 	module not found: org.scalaz.stream#scalaz-stream_2.11;0.7
[warn] ==== local: tried
[warn]   /home/hydra/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/home/hydra/tyrion/activator-1.2.10-minimal/repository/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[info] Resolving com.typesafe.trace#trace-sigar-libs;0.1.6 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalaz.stream:scalaz-stream_2.11:0.7
[warn] 		  +- org.specs2:specs2-common_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3
[warn] 		  +- org.specs2:specs2-matcher_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3
[warn] 		  +- org.specs2:specs2-core_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- org.specs2:specs2-analysis_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- org.specs2:specs2-matcher-extra_2.11:3.4-scalaz-7.0.6-20150414054958-dce2bc3 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- tyrion:tyrion_2.11:2014.1-DEV
sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:119)
	at sbt.IvySbt.withIvy(Ivy.scala:116)
	at sbt.IvySbt$Module.withModule(Ivy.scala:147)
	at sbt.IvyActions$.updateEither(IvyActions.scala:156)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
[error] Total time: 7 s, completed Apr 25, 2015 3:06:50 PM
```

**Comment by andyczerwonka** [comment]
@mbrigdan do a pull and run it again... does it work now?

**Comment by mbrigdan** [comment]
@andyczerwonka It looks like it found something new and downloaded it, but it still didn't update.
```
./activator-1.2.10-minimal/activator update
[info] Loading project definition from /home/hydra/tyrion/project
[info] Set current project to tyrion (in build file:/home/hydra/tyrion/)
[info] Updating {file:/home/hydra/tyrion/}tyrion...
[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7 ...
[warn] 	module not found: org.scalaz.stream#scalaz-stream_2.11;0.7
[warn] ==== local: tried
[warn]   /home/hydra/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/home/hydra/tyrion/activator-1.2.10-minimal/repository/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scalaz.stream/scalaz-stream_2.11/0.7/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalaz/stream/scalaz-stream_2.11/0.7/scalaz-stream_2.11-0.7.pom
[info] Resolving com.typesafe.trace#trace-sigar-libs;0.1.6 ...
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-core_2.11/3.5-scalaz-7.0.6/specs2-core_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-core_2.11;3.5-scalaz-7.0.6!specs2-core_2.11.jar (2203ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-matcher-extra_2.11/3.5-scalaz-7.0.6/specs2-matcher-extra_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-matcher-extra_2.11;3.5-scalaz-7.0.6!specs2-matcher-extra_2.11.jar (1157ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-analysis_2.11/3.5-scalaz-7.0.6/specs2-analysis_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-analysis_2.11;3.5-scalaz-7.0.6!specs2-analysis_2.11.jar (790ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-mock_2.11/3.5-scalaz-7.0.6/specs2-mock_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-mock_2.11;3.5-scalaz-7.0.6!specs2-mock_2.11.jar (915ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-junit_2.11/3.5-scalaz-7.0.6/specs2-junit_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-junit_2.11;3.5-scalaz-7.0.6!specs2-junit_2.11.jar (709ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.11/3.5-scalaz-7.0.6/specs2-matcher_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-matcher_2.11;3.5-scalaz-7.0.6!specs2-matcher_2.11.jar (3171ms)
[info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-common_2.11/3.5-scalaz-7.0.6/specs2-common_2.11-3.5-scalaz-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.specs2#specs2-common_2.11;3.5-scalaz-7.0.6!specs2-common_2.11.jar (2413ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalaz.stream:scalaz-stream_2.11:0.7
[warn] 		  +- org.specs2:specs2-common_2.11:3.5-scalaz-7.0.6
[warn] 		  +- org.specs2:specs2-matcher_2.11:3.5-scalaz-7.0.6
[warn] 		  +- org.specs2:specs2-core_2.11:3.5-scalaz-7.0.6 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- org.specs2:specs2-analysis_2.11:3.5-scalaz-7.0.6 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- org.specs2:specs2-matcher-extra_2.11:3.5-scalaz-7.0.6 (/home/hydra/tyrion/project/Build.scala#L30)
[warn] 		  +- tyrion:tyrion_2.11:2014.1-DEV
sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:119)
	at sbt.IvySbt.withIvy(Ivy.scala:116)
	at sbt.IvySbt$Module.withModule(Ivy.scala:147)
	at sbt.IvyActions$.updateEither(IvyActions.scala:156)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7: not found
[error] Total time: 25 s, completed Apr 25, 2015 3:57:19 PM
```

**Comment by andyczerwonka** [comment]
Jump onto the Gitter page https://gitter.im/andyczerwonka/tyrion
