### ISSUE TITLE
Internal server error when viewing site

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#95]
```
! @6m192cj87 - Internal server error, for (GET) [/api/summary/sites/553c153952189185171623a7] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "162,792"]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.lang.NumberFormatException: For input string: "162,792"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_20]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:1.8.0_20]
        at java.lang.Double.parseDouble(Double.java:538) ~[na:1.8.0_20]
        at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:284) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.collection.immutable.StringOps.toDouble(StringOps.scala:30) ~[org.scala-lang.scala-library-2.11.6.jar:na]
```
The above exception happens when I try to view the site. Possibly a strange reading in the database causing it?

**Comment by andyczerwonka** [comment]
@mbrigdan it's happening on a GET... hmnnn... have a look in the database to see if you can find it.

**Comment by mbrigdan** [comment]
@andyczerwonka Here's the readings collection https://gist.github.com/mbrigdan/5a0f8a321232aa9ddc77

**Comment by andyczerwonka** [comment]
@mbrigdan it's a legitimate bug... stand by

**Comment by andyczerwonka** [comment]
@mbrigdan go ahead a pull, I've put in a temporary fix for now to get you going.

**Comment by mbrigdan** [comment]
Looks like it worked
